name: aspect
channels:
  - conda-forge
  - defaults
dependencies:
  - myst-parser
  - pydata-sphinx-theme
  - sphinx-book-theme
  - sphinxcontrib-bibtex
  - pip>=20.1
  - pip:
    - sphinxcontrib-tikz
