name: github-docker

on: 
  push: 
    branches:
      - 'main'
  release:
    types: [created]

# If a merged PR triggers a rebuild of this docker image, and another
# PR is merged during the build, cancel the first of these since (i) this
# is a waste of time, and (ii) it creates a race condition with the
# upload.
concurrency:
  group: docker-build
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-docker:
    runs-on: ubuntu-latest
    if: github.repository == 'geodynamics/aspect'
    steps:    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_LOGIN }}

      - name: Build and push Docker image for main
        if: contains(github.event_name, 'push')
        uses: docker/build-push-action@v3
        with:
          context: ./contrib/docker/docker/
          cache-from: type=registry,ref=dealii/dealii:v9.4.0-focal
          cache-to: type=inline
          push: true
          tags: geodynamics/aspect:latest

      - name: Build and push Docker image for release
        if: contains(github.event_name, 'release')
        uses: docker/build-push-action@v3
        with:
          context: ./contrib/docker/docker/
          cache-from: type=registry,ref=dealii/dealii:v9.4.0-focal
          cache-to: type=inline
          push: true
          tags: geodynamics/aspect:${{github.ref_name}}

